### PR TITLE
LoginAndSignupUi

### LINKED ISSUE #232: Login and Signup page UI improvement
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like.

The login and Signup pages do not match the other page's UI. Can be improved.
3D illustrations can be used in place of 2D. The box effect that other pages follow can be implemented here. And the background effect can be added.

### Describe alternatives you've considered.

_No response_

### Additional context.

_No response_

### Show us the magic with screenshots

_No response_

### Checklist

- [X] I have checked the [existing issues](https://github.com/TechNodes2-0/ElectiveHub/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/TechNodes2-0/ElectiveHub/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

### PR DESCRIPTION
**Pull request by Annu117**
## Current behavior

The login and Signup page is not aligned with the theme.
Fixes #232 

## Proposed changes

Improved page design to match the theme. Added 3D vector.

## Checks

- [X] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Review by Yash636261 — CHANGES_REQUESTED** [review]
Form is not working and also the UI does not look appealing. can you improve it ?

**Comment by Yash636261** [comment]
try implementing this design:
image

**Comment by Annu117** [comment]
UI is matching with the theme. The design you shared does not align with other pages.
I can search for a better icon. Maybe the current one does not match the theme. It's pretty bright.

**Comment by Annu117** [comment]
see #302 
UI suggested doesn't match the theme.  The form is working now. Making a lot of changes will make the page too different from other pages. So, I considered the theme while designing. Had removed extra whites in many input boxes. Followed blue theme in dropdown role selection too.

**Comment by Yash636261** [comment]
>Making a lot of changes will make the page too different from other pages.

it would be fine we'll eventually move to better UI.

**Pull request closed without merging**
