### PR TITLE
Changed the  active state of nav bar links

### PR DESCRIPTION
**Pull request by swetha5157**
## Current behavior

- Before the changes the active state of navigation links were not working properly
- Eventhough we click Login or Signup the active link would be Home even the pages change.

## Proposed changes

Now after applying the changes, the active state of nav links is accurate,when home page is clicked home text is active and it follows for login and signup page

## Proposed Changes Video:

https://github.com/TechNodes2-0/ElectiveHub/assets/123291594/61144838-6518-467a-916c-c434f2d221de

The link of the issue is:  https://github.com/TechNodes2-0/ElectiveHub/issues/263
## Checks

- [X] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Review by Yash636261 — CHANGES_REQUESTED** [review]
try not to add unnecessary comments in code.

**Review by Yash636261 — APPROVED** [review]
Approving this.

If you've found value in the project and enjoyed making your contribution, I invite you to follow Us and star the repository. Your support means a lot and helps to further grow and improve the project. Thank you for your contributions!

Happy Coding!!

**Comment by swetha5157** [comment]
Made the changes as requested @Yash636261. I have removed unnecessary comment lines.
Kindly check it

**Comment by swetha5157** [comment]
Thankyou for merging my contribution @Yash636261

**Pull request merged**
