### PR TITLE
Improve   login  and Sign Up  page layout

### PR DESCRIPTION
**Pull request by GOURAVSINGH19**
## Current behavior

In which I change the layout of loign and sign up page ..

## Checks

https://github.com/TechNodes2-0/ElectiveHub/assets/120244528/cab5c447-b05d-4c3e-bcf8-3a952a876e72

If there is any mistake in my work then I apologise and tell me I will try to fix the issues.
if not then thanks for assigned to me.

### CODE REVIEW

**Comment by GOURAVSINGH19** [comment]
and I also remove the bottomtotop btn from signip and login page bez it not need..

**Review by Yash636261 — CHANGES_REQUESTED** [review]
Looks fine to me. 
can you just remove that illustration for smaller screen?  and also make fonts smaller for mobile screens.

**Comment by GOURAVSINGH19** [comment]
ok I will do it asap..

**Comment by GOURAVSINGH19** [comment]
@Yash636261 Done.

**Pull request merged**
