### PR TITLE
stats and newsletter enhancement- deployment issue fixed

### PR DESCRIPTION
**Pull request by mahekkg**
## Current behavior

Needed some improvement

## Proposed changes

Improved stats and newsletter section

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Comment by Yash636261** [comment]
Hey @mahekkg , I can't change I mentioned last time.
image

just make pull request here no need to create new one.

**Comment by mahekkg** [comment]
that is closed

**Comment by Yash636261** [comment]
> that is closed

actually, you closed that pull request.

no worries you can make change to this one.

**Comment by mahekkg** [comment]
> > that is closed
> 
> actually, you closed that pull request.
> 
> no worries you can make change to this one.

Changes are done you can review them and let ne know if change are required from my end

**Comment by Yash636261** [comment]
> Changes are done you can review them and let ne know if change are required from my end

I'm looking for these changes.
https://github.com/TechNodes2-0/ElectiveHub/pull/98#pullrequestreview-2051296489

**Comment by mahekkg** [comment]
image
It's solved

**Comment by Yash636261** [comment]
> It's solved

You missed color. 🙂

**Comment by mahekkg** [comment]
> > It's solved
> 
> You missed color. 🙂

okay, the previous color wasn't that appealing.
Will change it according to your needs .

**Comment by Yash636261** [comment]
> okay, the previous color wasn't that appealing.
> Will change it according to your needs .
> 
> Please review it

Even I think that colors are not that appealing, but it will look out of place to change colour too much from overall theme

You can create a new issue to change the color theme.  
🙂

**Comment by mahekkg** [comment]
okay , we can merge the current changes for now .

If you are looking for changing the theme is it for the whole app or just the home page?
As you suggested gray background with white text for the stats and newsletter section or overall look ?

Sure will create new issue as you said after the confirmation .

**Comment by Yash636261** [comment]
> As you suggested gray background with white text for the stats and newsletter section or overall look ?


That's what I was trying to say you. : )

**Comment by mahekkg** [comment]
> > As you suggested gray background with white text for the stats and newsletter section or overall look ?
> 
> That's what I was trying to say you. : )

It was a browser issue due light and dark mode 
image
I guess this is what you want?

**Review by Yash636261 — APPROVED** [review]
Approving changes.

Thank you for understanding and your efforts. Looking for more valuable contribution from you.

🙂

**Comment by Yash636261** [comment]
Will merge it up as soon as I resolve conflicts

**Pull request merged**
