### PR TITLE
Contri#85

### PR DESCRIPTION
**Pull request by GOURAVSINGH19**
Now I change the illusition and text  mobile visibility . If there is any issue please  tell me ..
Or If there is another work for me tell me.

https://github.com/TechNodes2-0/ElectiveHub/assets/120244528/c6db07db-82f7-4941-bce4-d3b9c7b439a0

### CODE REVIEW

**Comment by GOURAVSINGH19** [comment]
@Yash636261

**Review by Yash636261 — CHANGES_REQUESTED** [review]
need to size this illustration to it was before, this one is too small.
everything else is just fine.

image

**Comment by GOURAVSINGH19** [comment]
Screenshot 2024-05-12 125124
Done

**Review by Yash636261 — APPROVED** [review]
Looks cool! approving this.

If you've found value in the project and enjoyed making your contribute, I invite you to follow Us and star the repository. Your support means a lot and helps to further grow and improve the project. Thank you for your contributions!

Happy Coding!!

**Comment by GOURAVSINGH19** [comment]
welcome 
I will try to make more contributions in your project.😊

**Pull request merged**
