### PR TITLE
Update style of HomePage

### PR DESCRIPTION
**Pull request by safal45**
Screenshot from 2024-05-13 23-42-27
Screenshot from 2024-05-13 23-42-20

## Checks

- [ ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Comment by safal45** [comment]
please let me know if any updates are needed?

**Review by Yash636261 — APPROVED** [review]
Looks cool! approving this.

If you've found value in the project and enjoyed making your contribute, I invite you to follow Us and star the repository. Your support means a lot and helps to further grow and improve the project. Thank you for your contributions!

Happy Coding!!

**Comment by safal45** [comment]
Thank you for your approval and kind words! I'm glad to have had the opportunity to contribute to this project. I will definitely follow and star the repository to show my support. Looking forward to seeing the project grow and improve.

**Comment by safal45** [comment]
Could you please close this issue (#97), which has been resolved by PR #136?
I'm new to open source and learning more each day.

**Pull request merged**
