### PR TITLE
Added Icons and Rateus page

### PR DESCRIPTION
**Pull request by sailaja-adapa**
Hello Project Admin,
I Added Rate us page and Icons too - #289 
Kindly Please go through it @Yash636261

https://github.com/TechNodes2-0/ElectiveHub/assets/161804629/b1bda20d-d793-432b-8dea-76a05d5209ce

### CODE REVIEW

**Review by Yash636261 — CHANGES_REQUESTED** [review]
you have to handle dark mode also: 
image
image

**Comment by sailaja-adapa** [comment]
Yeah okk @Yash636261

**Comment by sailaja-adapa** [comment]
@Yash636261 is there already darkmode present in the project or should i need to Add that feature

**Comment by Yash636261** [comment]
> @Yash636261 is there already darkmode present in the project or should i need to Add that feature i'm not able to see the darkmode feature

dark mode button is not present but write your code for both dark and light mode as it uses the system default mode. you don't have to add any theme button as issue is already there for that.

**Comment by sailaja-adapa** [comment]
@Yash636261 I am new to contributions may be I can't do that

**Comment by Yash636261** [comment]
> @Yash636261 I am new to contributions may be I can't do that

okay than I will assign this issue to someone else.

**Pull request closed without merging**
