### PR TITLE
redesigned login signup pages

### PR DESCRIPTION
**Pull request by hamzailyas237**
Redesigned the login and signup pages from initial.

### CODE REVIEW

**Review by Yash636261 — APPROVED** [review]
I'm approving these changes.

**Comment by Nishitbaria** [comment]
give @hamzailyas237 100 Points

**Comment by Nishitbaria** [comment]
give @hamzailyas237  100 Points

**Comment by hamzailyas237** [comment]
> give @hamzailyas237 100 Points

Thanks @Nishitbaria

**Pull request merged**
