### PR TITLE
Added Contact Us form and about US section

### PR DESCRIPTION
**Pull request by VishalGaurav01**
Tries to match with the overall website theme and provide hover to the form

## Current behavior
No About and Contact Us page was present earlier on the website.

## Proposed changes
Added a fully responsive form with dark-themed UI with an about us section following it.
Used Tailwind flow bite framework for the UI designing.

## Checks

- [ ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Comment by Yash636261** [comment]
Just add some margins to placeholder, everything else seems good.

image

**Review by Yash636261 — APPROVED** [review]
Approving changes.

Thanks for your valuable contribution.

**Comment by Yash636261** [comment]
The form isn't working right now can you make it work. you can create new issue for that.

**Comment by VishalGaurav01** [comment]
the form will work 
need to add these details in the form.
image
I request you to follow the process to get these keys.
->Go to Web3form.com
->Select Work With tech "HTML Symbol".
->Enter your desired email address. Create Access Key
->You get a key in your Gmail.
->Send that key because with your credentials you will receive all the submit form details in your Gmail.
(Just Need the "value" key to make it work.

**Pull request merged**
