### PR TITLE
colour of navbar links changed

### PR DESCRIPTION
**Pull request by tanu-agarwal0101**
## Current behavior

image

## Proposed changes

image

## Checks

-  All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Comment by tanu-agarwal0101** [comment]
Newsletter enhanced
image
new Change
image

**Comment by Yash636261** [comment]
I saw you pull request, but because there are change in node modules it is impossible to review can you create new pull request and also delete node_modules from server as we don't need this.

**Comment by tanu-agarwal0101** [comment]
ok sir

**Comment by tanu-agarwal0101** [comment]
@Yash636261 please checkout pr #134

**Pull request closed without merging**
