### PR TITLE
Add About, Privacy Policy, Licensce and Contact Pages

### PR DESCRIPTION
**Pull request by Anshika040**
## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Comment by Yash636261** [comment]
Hey @Anshika040 ,Always mention the issue which are you closing with pull request.

**Comment by Anshika040** [comment]
Okay Sir

**Review by Yash636261 — CHANGES_REQUESTED** [review]
Hey @Anshika040 , I reviewed the code and added pages.

We cannot go with these changes as these pages are not matching with our color theme. can you please make changes to make it look more appealing.

you can take your time no need to hurry, also you can ask for help if you need any.

Regards

**Comment by Anshika040** [comment]
Ok, I will check.

**Comment by Anshika040** [comment]
I have made the changes please review it.
Screenshot 2024-05-14 222053

**Comment by Yash636261** [comment]
I am sharing few reference image you can make something like this then we can go with your pull request. Remove the policy page and contact us page is already done. so, you have only one page to complete.

Privacy policy page:
image

**Comment by Anshika040** [comment]
Ok, I will do it.

**Comment by Yash636261** [comment]
Hey @Anshika040, are you still working on this? Kindly reply within 72 hours otherwise issue will be assigned to someone else.

Thanks.

**Comment by Yash636261** [comment]
closing this...

**Pull request closed without merging**
