### PR TITLE
Elective subjects bug

### PR DESCRIPTION
**Pull request by Rohitha-pudu**
#118 
## Checks

- [ ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Comment by Rohitha-pudu** [comment]
> You don't have to push .env on github, you can remove it.



> You don't have to push .env on github, you can remove it.



> You don't have to push .env on github, you can remove it.

sorry forgot to ignore it

**Comment by Rohitha-pudu** [comment]
> You don't have to push .env on github, you can remove it.

done @Yash636261

**Review by Yash636261 — APPROVED** [review]
Looks cool! approving this.

If you've found value in the project and enjoyed making your contribution, I invite you to follow Us and star the repository. Your support means a lot and helps to further grow and improve the project. Thank you for your contributions!

Happy Coding!!

**Comment by Rohitha-pudu** [comment]
u  haven't added labels? @Yash636261

**Pull request merged**
