### PR TITLE
Update Navbar in Mobile View

### PR DESCRIPTION
**Pull request by safal45**
## Current behavior

In the mobile view, some styles of the navbar need to be updated. These changes will improve the navigation experience on smaller screens. Because there are buttons now, the button view is not so responsive in a row style.

## Proposed changes

I tried to make it responsive in a row, but with the addition of the "Contact Us" button, it doesn't look good in the mobile view. Therefore, I arranged the buttons in a column and also changed the order of the buttons in the mobile view. This looks more classic and is very responsive to small screen sizes.

Issue #146  is resolved in this PR.

## Checks

- [ ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Comment by safal45** [comment]
The final result is this. If any updates are needed, please let me know.
Screenshot from 2024-05-15 00-59-23

**Review by Yash636261 — CHANGES_REQUESTED** [review]
Great! everything seems perfect.

can you just make this close button visible.
image

**Comment by safal45** [comment]
Yeah sure

**Review by Yash636261 — APPROVED** [review]
Cool! Approving changes.

**Comment by safal45** [comment]
Hey, can you please add the label and the assignee to the pull request that I submitted? This is required so that the point is credited. Currently, the point is credited only if the label and the assignee are on the merged request. So, can you please add the label and the assignee to my two merged pull requests, #162 and #136?

**Comment by safal45** [comment]
@Yash636261

**Pull request merged**
