### PR TITLE
enhancement in stats and newsletter section

### PR DESCRIPTION
**Pull request by mahekkg**
## Proposed changes

Improved the stats and newsletter section in terms of visual presentation 

image
image

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Review by Yash636261 — CHANGES_REQUESTED** [review]
Reviewed your Pull Request. from design perspective it's looking good to me although I will suggest few improvements.

-Resolve this bug of overlapping of input text.
image

-Blue color and white color is not part of our color theme so change it gray to look symmetric to out home page

-Also, can you change this error message position as it is bit off.
image

**Comment by mahekkg** [comment]
Okay will work on it

**Comment by mahekkg** [comment]
Please review

**Comment by Yash636261** [comment]
Hey @mahekkg , deployment for your changes is failing. you have to look for this.

**Comment by mahekkg** [comment]
Hey can you guide me regarding the issue as I cannot see what's wrong.

**Comment by sohan-gupthak** [comment]
I would like to work on this issue Please assign me this issue under GSSoC'24
I have experience doing this.
LinkedIn - https://www.linkedin.com/in/sohan-guptha/
Mail - sohan.gupthak@gmail.com

**Comment by Yash636261** [comment]
> Hey can you guide me regarding the issue as I cannot see what's wrong.

okay, I'll check it up and reach out to once get some time.

**Comment by Yash636261** [comment]
Hey @mahekkg, This error is being displayed on vercel, there are issue from react-hot-toast library. you can remove it or use alternatives.

WhatsApp Image 2024-05-12 at 16 08 34_3eef1d8e

**Comment by mahekkg** [comment]
@Yash636261 can I generate a new pull  request?

**Comment by Yash636261** [comment]
> @Yash636261 can I generate a new pull request?

go for it!!

**Comment by mahekkg** [comment]
> > @Yash636261 can I generate a new pull request?
> 
> go for it!!

Thanks,
https://github.com/TechNodes2-0/ElectiveHub/pull/115

**Pull request closed without merging**
